services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    depends_on:
      - python
    ports:
      - "8086:8086"
    networks:
      - influxdb_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${TOKEN}

  python:
    build: .
    container_name: swpc_monitoring
    networks:
      - influxdb_network
    env_file:
      - .env

networks:
  influxdb_network:

volumes:
  influxdb-volume:
